### ISSUE TITLE
ReferenceError: Can't find variable: crypto

### ISSUE THREAD

**Issue by kliyadongkingkk** [CodyJasonBennett/r3f-native-starter#7] opened 2022-04-22 07:07 UTC
Sorry, my English is not very good. I use the translation software.

I downloaded the code

yarn

yarn start 

Terminal:
`ReferenceError: Can't find variable: crypto
at node_modules\react-native\Libraries\LogBox\LogBox.js:149:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:60:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:34:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:172:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\@react-native\polyfills\error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules\metro-runtime\src\polyfills\require.js:204:6 in guardedLoadModule
at http://192.168.150.57:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:302215:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules\react-native\Libraries\LogBox\LogBox.js:149:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:60:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:34:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:172:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\@react-native\polyfills\error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:367:8 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:112:4 in callFunctionReturnFlushedQueue
`

android devices:
![Screenshot_2022-04-22-14-59-55-005_host exp exponent](https://user-images.githubusercontent.com/95637740/164623386-7f689074-fbe2-4da2-81b7-241dedd11029.jpg)

I use Expo to run Android

Can you help me?

**Comment by danielseow-bjak** [comment] 2022-05-13 04:49
Same error I'm having, not sure how can I solve this issue

**Comment by CodyJasonBennett** [comment] 2022-05-13 06:23
Looking into this, seems to be a regression since introducing `nanoid` in Drei. Can prob defer to `THREE.MathUtils.generateUUID` or one of my crypto polyfills.

**Comment by CodyJasonBennett** [comment] 2022-05-13 06:50
Fixed in Drei `9.7.2`. I updated master's deps.

**Closed by CodyJasonBennett** 2022-05-13 06:50 UTC
